baseURL: "https://tigxy.github.io/"
title: Christian Ganhör
# paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Portfolio
  # description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false
  extend_head: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # https://www.flaticon.com/free-icon-font/brain-circuit_8778000?page=1&position=2&term=artificial+intelligence&origin=search&related_id=8778000
    favicon: "/brain-circuit.svg"
    favicon16x16: "/brain-circuit.svg"
    favicon16x16: "/brain-circuit.svg"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
    customCSS:
      - css/custom.css
      - css/homepage.css
      - css/work.css
      - css/site.css
      - css/education.css
      - css/logos.css
      - css/timeline.css

  label:
    text: "Christian Ganhör"
    # iconSVG: <svg ></svg>
    # iconSVG: '{{ (resources.Get "icons/brain-circuit.svg").Content | safeHTML }}'
    iconSVGPath: icons/brain-circuit.svg
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    #title: '<span class="typewriter">Hi there, welcome to my webpage!</span>'
    title: |
      <div class="headline-container">Hi there, welcome to my webpage!</div>
      <div class="subheadline-container"><p>Explore to find out about me, my projects, and more.</p></div>
    # subtitle: "Here you can find out all about my background, projects and professional life."
    imageUrl: "profile.png"
    imageWidth: 180
    imageHeight: 180
    # imageTitle: This is me!
    # buttons:
    #   - name: Posts
    #     url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    # find more social icons here: https://github.com/adityatelange/hugo-PaperMod/wiki/Icons
    - name: github
      url: "https://github.com/tigxy"

    - name: linkedin
      url: "https://www.linkedin.com/in/christian-ganhoer"

    - name: googlescholar
      url: "https://scholar.google.com/citations?user=kP4hSv8AAAAJ&hl=de"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: work
      name: work
      url: /work/
      weight: 1
    - identifier: education
      name: education
      url: /education/
      weight: 2
    - identifier: timeline
      name: timeline
      url: /timeline/
      weight: 3
    # - identifier: projects
    #   name: projects
    #   url: /projects/
    #   weight: 3
    # - identifier: papers
    #   name: papers
    #   url: /papers/
    #   weight: 4
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON